### ISSUE TITLE
General error creating mysql trigger

### ISSUE THREAD

**Issue by jamespsterling** [dan-da/cdc_audit#1] opened 2015-12-15 15:40 UTC
I'm having an issue with the `FOR EACH ROW BEGIN` loop wrapping the insert statement. If I remove the `BEGIN` and `END`, creating the trigger works just fine. 

Using mysql 5.5. 

``
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3

``

Working example,

`
DELIMITER @@
CREATE TRIGGER `rate_types_after_insert` AFTER INSERT ON `rate_types`
 FOR EACH ROW
  insert into `rate_types_audit` (`id`, `type`, `audit_event`, `audit_timestamp`) values(NEW.`id`, NEW.`type`, 'insert', CURRENT_TIMESTAMP);
@@
`

**Comment by dan-da** [comment] 2015-12-22 00:09
Thanks for the report.

Hmm....  the BEFORE and END are used in case the table previously had another trigger (not from cdc_audit).  In that case, the old trigger lines are inserted after the new trigger.  And BEFORE .. END are required for multi-statement triggers.

If that situation does not apply to you, you could certainly remove the BEFORE .. END in cdc_audit_gen_mysql.php as a workaround.  see function: write_audit_triggers()

Still, I don't understand yet why you see that error.  I am using mysql 5.5.38 from Ubuntu 14.04 and it does not give any error or warning.

Further, the documentation for 5.5 indicates that BEGIN .. END is correct usage for triggers.  see:
http://dev.mysql.com/doc/refman/5.5/en/create-trigger.html
http://dev.mysql.com/doc/refman/5.5/en/begin-end.html

If you could provide a complete test case with a sample database containing 1 table, perhaps I could replicate it here.

**Comment by dan-da** [comment] 2015-12-22 00:28
I just made the following test, attempting to duplicate your table structure.  I could not replicate the error.

create table rate_types (
id integer primary key,
type integer
);
Query OK, 0 rows affected (0.02 sec)

$ ./cdc_audit_gen_mysql.php -d hoover_visitor_bucket_go_1 
Successfully Generated Audit Tables + Triggers in ./cdc_audit_gen

$ mysql -u root hoover_visitor_bucket_go_1 < cdc_audit_gen/rate_types.audit.sql

( no error )

"show triggers" shows that the triggers were created successfully.

**Comment by dan-da** [comment] 2015-12-26 20:58
Closing this.  Could not reproduce.  Please open a new issue if/when you provide a test-case demonstrating the issue.

**Closed as completed by dan-da** 2015-12-26 20:58 UTC

**Comment by jamespsterling** [comment] 2016-01-15 18:44
If change the `FOR EACH ROW BEGIN` to just `FOR EACH ROW` it works just fine. Something about my mysql instance (Server version: 5.5.46-0ubuntu0.12.04.2) doesn't like the begin. 

Example:

```
        $triggers_mask = <<< 'END'
-- %1$s after INSERT trigger.
DELIMITER @@
CREATE TRIGGER `%1$s_after_insert` AFTER INSERT ON `%1$s`
 FOR EACH ROW 
  insert into `%2$s` (%3$s) values(%4$s);

%7$s
 END;
@@
```

**Comment by dan-da** [comment] 2016-01-15 18:47
which version of mysql are you using?

A complete test case adequate for reproduction would be a full database dump.  Eg, create a test db with a test table.  run cdc_audit against it.   If it fails, then do a mysqldump of the entire test db and attach it here, with mysql version used.  If it doesn't fail, then there must be something special about the DB you are presently using, so we can begin to narrow it down...

**Comment by jamespsterling** [comment] 2016-01-15 18:51
Server version: 5.5.46-0ubuntu0.12.04.2

I've attached the generated sql file. 
[test.audit.sql.txt](https://github.com/dan-da/cdc_audit/files/92344/test.audit.sql.txt)

**Comment by dan-da** [comment] 2016-01-15 19:03
The test file you provided is incomplete because you didn't dump the entire DB and thus the original test table does not exist.

mysql -uroot test < /tmp/test.audit.sql.txt 
ERROR 1146 (42S02) at line 35: Table 'test.test' doesn't exist

**Comment by jamespsterling** [comment] 2016-01-15 19:55
Here's the db dump [test.sql.txt](https://github.com/dan-da/cdc_audit/files/92444/test.sql.txt)

**Comment by dan-da** [comment] 2016-01-15 20:19
thanks.   for me, both of these files import without warning or error.

$ mysql -uroot test < /tmp/test.sql.txt 
$ mysql -uroot test < /tmp/test.audit.sql.txt 

$ mysql --version
mysql  Ver 14.14 Distrib 5.5.38, for debian-linux-gnu (x86_64) using readline 6.3

dpkg -l | grep mysql-server | head -n 1
ii  mysql-server                                  5.5.38-0ubuntu0.14.04.1

It seems worth noting that your mysql version is 5.5.46 on ubuntu 12.04.2, while mine is only 5.5.38 on a newer ubuntu 14.04.1.   Both long-term support releases.

This makes me wonder if perhaps you are using mysql from a PPA rather than the standard ubuntu package?    If so, maybe it has a weird bug causing this.  just a theory.

again, BEGIN .. END is standard syntax for triggers according to the mysql docs (linked in comment above).  This feels like a problem with your installation somehow.  Do you have access to another mysql instance to test with?    Or you could try installing a different release/package.

**Comment by jamespsterling** [comment] 2016-01-20 17:02
I may have updated Mysql with a PPA. I'll have to play around with an updated version or a new VM with 14.04 or some other flavor. 

Thanks for your feedback!
